/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java;

import java.service.ReportService;

public class App {
    static ReportService service;

    public static void main(String[] args) {
        service = new ReportService();

        try {
            service.generateReport("CellPhone.csv", "CellPhoneUsageByMonth.csv");
        } catch(Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
